### ISSUE TITLE
Nodes and Navs not removed from DB when deleting NAV in CP.

### ISSUE THREAD

**Issue by Osze** [verbb/navigation#111]
### Description

Nodes and Navs not removed from DB when deleting NAV in CP.

Throws error when saving entry that was active in an old/deleted NAV.

### Steps to reproduce

1. Deleting nav in CP
2. Saving Entry that was active in old/deleted nav.
3. Throws an error not finding Nav ID.

### Additional info

Multi Site YES

- Plugin version: 1.1.13
- Craft version: Craft CMS 3.3.15

**Comment by engram-design** [comment]
They actually won't get deleted from the database, because nodes and nav's support soft-deletes. There was an issue when saving new navs with a deleted handle (see https://github.com/verbb/navigation/issues/110), but that sounds only half of your issue.

I wasn't able to replicate the error message when saving an entry. Would you be able to send through a screenshot, or the full stack trace of the error? Just trying to hone in on it.

Might be worth quickly trying [1.1.14](https://github.com/verbb/navigation/releases/tag/1.1.14)
