### ISSUE TITLE
Relative URLs should be passed through Craft's url() function

### ISSUE THREAD

**Issue by benface** [verbb/navigation#115]
When using a "Custom URL" node and entering a path instead of a full URL, I feel like the URL that gets rendered on the front-end should be the result of the path being passed through Craft's `UrlHelper::url()` function (which is the same function that gets exposed to Twig).

For instance, if I enter the URL "shop", I would expect the node to render `<a href="https://my-sites-base-url.com/shop">`, and not simply `<a href="shop">` which won't work properly if the current URL is deeper than the base URL.

**Comment by engram-design** [comment]
Updated in [1.2.0](https://github.com/verbb/navigation/releases/tag/1.2.0)

**Comment by engram-design** [comment]
FYI, I'm reverting this behaviour in [1.3.1](https://github.com/verbb/navigation/releases/tag/1.3.1) and [1.2.8](https://github.com/verbb/navigation/releases/tag/1.2.8). There's just too many edge-cases to deal with, and I think the simplest solution is to just add a proceeding `/` to a URL to have it be an absolute URL.

Otherwise, using an alias `alias('@web/shop')` is a handy option.

Sorry to back-flip on this.

**Comment by benface** [comment]
No worries, thanks for considering it @engram-design!
