### ISSUE TITLE
[1.2.0] Unable to edit existing nodes

### ISSUE THREAD

**Issue by nixondesigndev** [verbb/navigation#122]
### Description

When trying to edit an existing node I get the "An unknown error occurred" flash message. This navigation existed pre 1.2 but also occurs on new navigations as well.

### Steps to reproduce

1. Create new navigation
2. Add node
3. Click on cog

### Additional info

- Plugin version: 1.2.0
- Craft version: Craft Pro 3.3.19

**Comment by engram-design** [comment]
Are you an admin trying to edit a nav, or a non-admin? There were new permissions added for edit/delete navigations, which sounds like this might be the issue.

Otherwise, can you look at your web console (Network tab in Chrome) and look at the request to `actions/navigation/nodes/save-node` and report back the Preview result?

**Comment by nixondesigndev** [comment]
Logged in as an admin. When clicking on the cog icon the `actions/navigation/nodes/editor` controller is called resulting in a 500 with the response `{"error":"Unknown \"displayName\" function."}`. I have two node types Entry and Manual both result in the same error.

**Comment by engram-design** [comment]
Ah, sorry about that - didn't realise this was a non-standard Twig function, as it was included in one of the other plugins I had installed (Field Manager).

Fixed in [1.2.2](https://github.com/verbb/navigation/releases/tag/1.2.2)
