### ISSUE TITLE
note: urls beginning in # will be overridden to start with a /#

### ISSUE THREAD

**Issue by dlindberg** [verbb/navigation#128]
### Description

1.3.0-RC1 for certain and probably back to 1.2.0 will not allow a link to start with a `#`, from the change to using Craft's `url()` function. This behavior does break links if the expectation is that a manual link is treated as a string.  Which was unexpected from the way the release notes were phrased. In my specific use case, causing dropdown menus to fail (fixing the dropdown implementation to follow best practices is on my todo list). Mostly noting the issue so if someone else runs into the issue they spend slightly less time scratching their head then I did...

### Steps to reproduce

1. start a url with # and save
2. url will start with a /#

### Additional info

- Plugin version: 1.3.0-RC1 (probably since 1.2.0)
- Craft version: 3.4.0-RC1.1

**Comment by engram-design** [comment]
Damn, I actually didn't test using a '#'. This wasn't supposed to be a breaking change, but that was pretty wishful thinking.

Fixed in [1.2.5](https://github.com/verbb/navigation/releases/tag/1.2.5), but you'll need to re-save any custom nodes, as it will have set them to `/#your-url`

https://github.com/verbb/navigation/issues/115
