### ISSUE TITLE
Update from craft 3.3.16.1 migration not working.

### ISSUE THREAD

**Issue by johnwbaxter** [verbb/navigation#142]
I'm having the same issue as this now closed ticket - https://github.com/verbb/navigation/issues/133

The 1.3.2 does not fix this for me.

**Comment by engram-design** [comment]
Is the error exactly the same? Can you share the full error exception?

I assume you're updating to the latest Craft + Nav versions?

Any change of getting a database snapshot?

**Comment by johnwbaxter** [comment]
Yep, same error.
Yep, updating to latest Craft & Nav versions.
Yeah, I can give you a DB snapshot. Where do you want me to send it?

**Comment by sjcallender** [comment]
I'm seeing the same error when trying to update from Navigation 1.0.15. I've tried it with different versions of Craft too, from 3.1.34.3 to 3.3.20.1.

**Comment by engram-design** [comment]
@johnwbaxter to web@verbb.io

@sjcallender if you're able to do the same? Just can't seem to replicate the damn thing!

**Comment by johnwbaxter** [comment]
@engram-design Ok, I have sent you the DB dump via wetransfer referencing this issue url in it.

**Comment by sjcallender** [comment]
I got it working by upgrading to Craft 3.4.9, then Navigation 1.0.18, then Navigation 1.3.6.

I still have the db dump and composer.json/.lock from the version it was failing on. I'll shoot those over.

**Comment by engram-design** [comment]
I'm not sure about @sjcallender, but with @johnwbaxter case, this was due to using `./craft update all` to upgrade Craft and associated plugins, instead of composer natively (as I was doing, and typically do).

The reason is that Craft resolves the following updates need to be done:

```
craft 3.3.16.1 => 3.4.10
navigation 1.1.13 => 1.2.8
```

This is actually incorrect, as it should be resolving navigation to 1.3.6 (the latest at this time). But because the 1.3.x branch requires Craft 3.4.x, at the time of update, its resolving that it can't update past 1.2.8. In fact, once performing the updates, you have to run `./craft update all` a second time in order to get all updates limited to Craft 3.4.x (in our case, to update navigation from 1.2.8 to 1.3.6)

I feel like this might be a craft update issue. Normally I would have loose version requirements in my composer.json file, and perform `composer update` and all the dependancies work themselves out correctly. I wonder if there is anything to be done here? cc @brandonkelly

In the meantime, this is fixed thanks to a [1.2.9](https://github.com/verbb/navigation/releases/tag/1.2.9) release that's compatible with Craft 3.1+, that contains these critical fixes that occur during updates. @johnwbaxter, run the `./craft update all` again and you should be okay
