### ISSUE TITLE
Changed title not respected in breadcrumbs function

### ISSUE THREAD

**Issue by bertoost** [verbb/navigation#155]
### Description

When I'm using `craft.navigation.breadcrumbs()` function, it is not respecting the customized title set for a node in the navigation.
Is this something I need to do myself?

### Additional info

- Plugin version: 1.3.15
- Craft version: 3.4.20

**Comment by engram-design** [comment]
This is correct behaviour for the moment. The breadcrumbs functionality doesn't actually use the Nodes layout at the moment, instead determining elements from the page's segments.

The reasoning behind this is because while a navigation is collecting your elements into a navigation, it doesn't always define the actual content structure (sitemap or information architecture) of your site, in the way that sections do.


In addition, you'd to provide navigation nodes for every possible URL for your site in order for this to work as expected.

It's something I might look at changing, but I'll have to be considerate of current people using this function.
