### ISSUE TITLE
[FR] import navigation nodes via feed me

### ISSUE THREAD

**Issue by vnali** [verbb/navigation#163]
**Description**
is it possible to import nodes to navigation via feed me plugin in future?
usually other content management system's have menus and this is cool to convert those menus to Craft and Navigation.
thanks.

**Comment by engram-design** [comment]
Not currently possible, but will look to add support for Feed Me in the future.

**Comment by gazsp** [comment]
Adding my support for this request - it would save me hours of data entry right now...

**Comment by engram-design** [comment]
So my only concern is the complexity of this integration, namely because a navigation node itself is pretty complicated. Say you're importing from something like Wordpress where your nodes might reference Pages. Those pages won't exist in Craft, so how should we create a navigation node to link to that non-existant entry? We could maybe do matching on titles of entries, but that's hardly ideal.

There's a lot to consider here, but [1.4.0](https://github.com/verbb/navigation/releases/tag/1.4.0) adds some simple support. Basically, everything is imported as a manual node.

If there's enough demand, and we get some community feedback with how best to handle specific scenarios, we'll address them as we go.

**Comment by vnali** [comment]
@engram-design i totally agree about links and actually in my case i don't need navigation to do anything about links. i preprocess menus and specially links with custom codes before importing via feed-me.
