### ISSUE TITLE
syntax error, unexpected '?' in /vendor/symfony/yaml/Parser.php

### ISSUE THREAD

**Issue by tyssen** [verbb/navigation#186]
**Description**
With any navigation nodes enabled in my templates, I get:

> syntax error, unexpected '?' in /vendor/symfony/yaml/Parser.php

If I follow the stack trace down, I eventually get to the first instance of a navigation node. If I comment them all out, the site comes back. I've just upgraded this site to Craft 3.5.7.

I only get this on the staging server, not on my local dev environment.

**Steps to reproduce**
1. Load any page with any navigation included and get the above error.
2. Comment out all navigation nodes and the page comes back.

**Additional info**
- Plugin version: 1.3.27
- Craft version: 3.5.7
- Multi-site: No

**Comment by engram-design** [comment]
Can you let me know your PHP version on your staging site?

**Comment by tyssen** [comment]
7.0.33

**Comment by engram-design** [comment]
I can't seem to replicate this on a fresh 7.0.33 install with just Navigation installed. Are you able to send through the full stack trace? I'm trying to figure out which part of Navigation is triggering this, as that file isn't a dependancy Navigation directly uses.

Can you just check your `composer.json` contains the PHP constraints? https://github.com/craftcms/cms/issues/4365#issuecomment-499197554

**Comment by tyssen** [comment]
[Stacktrace attached](https://github.com/verbb/navigation/files/5149942/stacktrace.txt). And yes I have the platform PHP set to 7.0 in `composer.json`.

**Comment by engram-design** [comment]
Can you delete your vendor folder, `composer.lock` file and run `composer update`?

There's no line `1111` in `symfony/yaml/Parser.php` for the package that's PHP 7.0 compatible, as Brandon mentions. For instance, in the test site I just did, it's got `v3.3.6` installed, because I've restricted the packages to be PHP 7.0 compatible.

However, for another test site, I have no PHP constraints in my `composer.json` file, and it's loaded `v4.4.11`. That does have a line `1111`.

It sounds like it's resolved the wrong package for your PHP constraints. Likely because you have a higher PHP version installed locally, so its resolved to that, whilst your production site might be on something different?

**Comment by tyssen** [comment]
All good now. 👍
