### ISSUE TITLE
Nodes overwritten by site homepage

### ISSUE THREAD

**Issue by Nielsvdel** [verbb/navigation#195]
**Description**
When you save the navigation the nodes from another multisite. The nodes get overwritten by the homepage of the current site.

**Steps to reproduce**
1. Go to navigation of site 1
2. Add entry from site 2
3. Go to the navigation of site 2
4. Edit this navigation by adding an entry from site 1
5. Go back to the menu of site 1
6. Links and title's are overwritten with the link and title of the homepage from the current site

**Additional info**
- Plugin version: 1.3.29
- Craft version: 3.4.15
- Multi-site: Yes

**Comment by engram-design** [comment]
Can you advise if you have "Propagate nodes across all enabled sites?" set to on or off?

**Comment by engram-design** [comment]
Wondering if you can confirm the following video to ensure I'm replicating correctly? I can't seem to replicate your error.

The below video shows the "Default Site" as the primary site, and "Australia" the second site. I'm adding the homepage single entry, adding the alternate site entry into the navigation as you describe (site 1 entry into site 2 nav, etc).

https://d.pr/v/SwTp0e

**Comment by Nielsvdel** [comment]
Hello,

To answer your question on the previous mail: Yes propagate nodes across
all enabled sites is enabled. I have added a video to show you the issue i
have. Hope it becomes clear! Thanks for responding!

Met vriendelijke groet,

Niels van der El
*Front-end Developer*



Op zo 27 sep. 2020 om 10:59 schreef Josh Crawford <notifications@github.com

**Comment by engram-design** [comment]
I'm not sure if that video came through, sorry.

And, if you have "Propagate nodes across all enabled sites?" enabled, then all nodes across all your sites should be exactly the same, so not quite sure how they can be different...

**Comment by Nielsvdel** [comment]
I have added 2 images and the video again, hope it comes through.

I'll try to explain better. I add all the homepages (entry) from the other
sites in one menu: let's call it menu 1 (filename: menu 1), then when i
switch to a menu from one of the other sites it should be exactly the same
as menu 1 because propagate nodes across all enabled site is enabled. But
instead it looks like (filename: menu 2).

**Comment by engram-design** [comment]
Sorry they didn't come through again, might be because you're replying via email, instead of commenting via Github?

**Comment by Nielsvdel** [comment]
![menu 1](https://user-images.githubusercontent.com/71633890/94433156-2a397f00-0198-11eb-8e05-e4b043688af8.png)
![menu 2](https://user-images.githubusercontent.com/71633890/94433163-2dcd0600-0198-11eb-830b-f8e3a910f7f6.png)

**Comment by engram-design** [comment]
Thanks, all good now! So just to confirm those entries - you mention they're all the homepages? I'm just a bit confused on that point, as there's typically only a single homepage per site? Or is these just _any_ entries?

**Comment by Nielsvdel** [comment]
It is a multisite and has a footer menu, in the footer menu i add the homepage of all the other multisites from the same language. In my case when i am on the site called "signing" i add the homepage from the sites: Monitoring, Service and clocks. But then when i go to the menu of Monitoring, Service or clocks (the other multisites) it isn't saved like it should. (see image 2 where every node is called clocks). It should be exactly the same as the menu on the first image.

**Comment by engram-design** [comment]
Thanks for all the clarifications, I can reproduce this. It's actually expected behaviour, so changing this will be a breaking change.

The idea behind this was that if you have propagation set for the menu and add an entry in one site, it should reflect the respective site element in all your other sites.

So for example you might have a page named "About Us" in Site 1, but called "Who We Are" in Site 2. You add the "About Us" element in Site 1, and with propagation on, it will also add "Who We Are" in Site 2's nav - not "About Us" as you might expect.

Both approaches are somewhat valid. When you're building a multi-site menu, you could start populating elements on one site, but you don't want the same elements from Site 1 to be on all your other site's menus. Instead, you'd want the other site's menus to reflect the elements in their respective sites. But then in your case, you want to pick a specific entry for a site, and that should be the same across all your menus.

I'll have to make this opt-in for the moment until a breaking release. You can use the `propagateSiteElements` config setting and set this to false to get your expected behaviour.

See [1.3.31](https://github.com/verbb/navigation/releases/tag/1.3.31)
