### ISSUE TITLE
Eager loading element

### ISSUE THREAD

**Issue by ilicmarko** [verbb/navigation#212]
**Description**
Is there a way to eager load elements in  `children`?

You can eager load the children and that works as it should

```twig
{% set nodes = craft.navigation
  .nodes('headerNavigation')
  .level(1)
  .with(['children'])
  .all()
%}
```

But I use the description and icon from the actual element. This creates a lot more queries (20+) in my case. I would like to eager load the element on a certain level (1 level deep is my max).

I tried everything and no go, `children.element` and `element`

Is this even possible?

Maybe (a bit) related to #191.

**Comment by chadcrowell** [comment]
+1 to eager load related elements for the node.element

**Comment by engram-design** [comment]
I'll look into this, I'm not _quite_ sure how feasible it'll be.

**Comment by engram-design** [comment]
After chatting with the Craft crew about this, it's not possible at the moment, although it'd be great! We'll need to wait for eager-loading to support querying multiple element types. At the moment, it's just not possible to eager-load the element related to a node. https://github.com/craftcms/cms/issues/1820#issuecomment-479188472

**Comment by MoritzLost** [comment]
@engram-design I just ran into this as well – is this possible nowadays? I also need to check the actual element linked to the `node`, and this results in a bunch of extra queries …

**Comment by engram-design** [comment]
I believe it's still not possible, but it's also on the Craft team's radar now more than ever, due to the Matrix nested refactoring, and Commerce's Product/Variant nesting implementation.

**Comment by MoritzLost** [comment]
@engram-design Thanks, I'm looking forward to this 👍 

Just thinking out loud – what about a utility / service method to load all elements for an array of nodes at once, and set them on the nodes so that accessing `node.element` will not require additional queries? Then I could call this method in my Twig template and only add one query to my page, instead of having the N+1 problem.

Something like this:

```twig
{% set nodes = craft.navigation.nodes('primary').all() %}
{% do craft.navigation.loadNodeElements(nodes) %}
```

Or maybe this could be done using an optional parameter for node queries (e.g. `Node::find()->withRelatedElements()->all()`) that does this in the `NodeQuery::populate()` method?
