### ISSUE TITLE
Custom URL node - add autocomplete for aliases and ENV variables

### ISSUE THREAD

**Issue by piotrpog** [verbb/navigation#213]
I noticed that e can use aliases in custom URL nodes, which is really helpful. But it would be even better if there was autocomplete functionality, like there is for example in assets settings:

![image](https://user-images.githubusercontent.com/42622545/97684030-e7214300-1a98-11eb-96e4-430e81b9cee1.png)

And there should be maybe some short information added that we can use aliases.

**Comment by engram-design** [comment]
I'm not sure suggesting you can use aliases is overly helpful for content editors. Makes sense for developers of course. In addition, the autosuggest field will suggest _all_ aliases (or env settings if allowed), which aren't URLs.

I think adding an alias as a URL would be something you wouldn't often do. Rather than suggesting to use an available alias every time you start typing, it's probably not the first preference for regular manual URL usage for nodes.

Your screenshot shows a good example. What's to prevent an unwitting client from selecting `@webroot`?

**Comment by engram-design** [comment]
Going to close this as something I'm probably not going to implement, for the reasons stated above. I would very much suggest a custom node type to achieve this. I believe it's just too risky providing access to **all** aliases, most of which wouldn't be URLs.
