### ISSUE TITLE
Add parameter to check if node has an URL

### ISSUE THREAD

**Issue by nixondesigndev** [verbb/navigation#216]
**What are you trying to do?**

When performing element queries it would be helpful to be able to get only nodes that have URLs. This would help in scenarios when the user has edited a node after creating and removed the element resulting in the node not having an URL.

```
{% set myQuery = craft.navigation.nodes() %}
```

**What's your proposed solution?**

Add either a new parameter for checking for URLs or add `url` that allows for the same `':notempty:'` pattern as Craft. 

```
{% set myQuery = craft.navigation.hasUrl().nodes() %}
```

or 

```
{% set myQuery = craft.navigation.url(':notempty:')nodes() %}
```

**Additional context**

Plugin version: 1.4.2

**Comment by engram-design** [comment]
This might be a bit tricky, mostly because URLs are determined after the initial querying happens, just because there are many ways to define URLs (manual, custom type, elements, etc).

However, I've managed to pull this off in a suitable way. You can use `{% set myQuery = craft.navigation.hasUrl().nodes() %}` in [1.4.3](https://github.com/verbb/navigation/releases/tag/1.4.3)
