### ISSUE TITLE
Multi-Site Enabled Sites isn't respected.

### ISSUE THREAD

**Issue by jhubb-io** [verbb/navigation#222]
**Description**
We have multiple sites set up as follows:
Campaigns - handle (campaigns)
Default - handle (default

When we set up a navigation enabled for only Default with propagate nodes off then add a node it's actually added to Campaigns and the default site shown for that navigation is Campaigns rather than the one that's actually enabled.

**Steps to reproduce**
1. Set up multisite exactly as above
2. Add a test navigation enabled only for Default
3. Add a node to the navigation
4. In Settings enable the navigation for Campaigns
5. Go back to the navigation, you'll see the node was actually added in Campaigns and not Default

**Additional info**
- Plugin version: 1.4.3
- Craft version: Craft Pro 3.5.15.1
- Multi-site: Yes
- Propagate nodes: Yes and No

**Additional context**
Video showing behaviour
https://a.cl.ly/RBu97XzQ

**Comment by engram-design** [comment]
So I think the core issue of this is that in amongst all the disabling/enabling of sites, you could actually technically directly access the nodes of a site that wasn't enabled. If you had the direct URL to it, which you would've if you were on a page editing nodes for one site, disable it and refresh - you're still on that page.

In addition, we weren't checking against the enabled sites for a nav, just the enabled sites for the user, so there was unexpected results there.

Should be fixed in [1.4.4](https://github.com/verbb/navigation/releases/tag/1.4.4)
