### ISSUE TITLE
Saving with a Per-Site Multi-Site Navigation causes missing and duplicate entries on other sites

### ISSUE THREAD

**Issue by thinkflo** [verbb/navigation#228]
**Description**

I am currently evaluating your plugin for purchase and would happily by and subscribe however, I am hitting a major usability issue that weighs on my decision to purchase.

I have 2 sites setup in a multiple site setup in different languages, English and French.   The French Navigation menu has different requirements than the English.  Not all of the Navigation Nodes are available in French versus the English.  Therefore, in order to save an alternate menu per Site, in `Settings`, I have to disable `Propagate nodes across all enabled sites`.  Then I disable the `Enabled for site` setting on the selected nodes that are not available in that particular language.

Now, with propagation disabled, whenever I make changes to an existing node, it disappears on the other site once I save.  Conversely, when I add a new entries on one site, a duplicate entry appears on the other site.  This behaviour makes the plugin unusable for a regular content author.

The desired affect should be that with the switch disabled, the Navigation menus should become independent of each other and not affect the other when changes are made.  When enabled, the changes should be applied to both sites, including translatable fields.  

**Steps to reproduce**
1. Create a Navigation menu including some test nodes with parents in a multi-site setup with `Propagate nodes across all enabled sites` enabled
2. Then, disable that setting
3. Now, disable a node on one site by editing it and disabling the `Enabled for site` setting of the node and Save
4. Add a new node entry and Save your changes
5. Switch to the other Site using the Dropdown in the Navigation menu, and see missing or duplicate nodes being added due to the previously actions on the other Site

**Additional info**
- Plugin version: 1.4.7
- Craft version: 3.5.16
- Multi-site: Yes
- Propagate nodes: Yes & No

**Comment by engram-design** [comment]
The problem here is that switching between the two methods isn't exactly encouraged. For instance, say you have two completely independent navigations with Propagate disabled. What happens when you decide to enable it - do all your navigations become exactly the same, hence nodes are deleted?

But in this case, there's room for improvement. Navigation should detect when you want to stop propagating nodes, and populate all other sites with the same nodes at that point in time. From that point onwards, the nodes are independent. 

The problem I have is that it's not just propagating the same entry across multiple sites, you're actually un-hooking sites functionality with nodes. Each node is its own element are aren't related to each other.

In practice, this means we need to create a new element for every node in the primary sites' navigation, and create a copy in each sites's navigation exactly as per the primary sites' navigation.

Should be improved in [1.4.8](https://github.com/verbb/navigation/releases/tag/1.4.8)

**Comment by thinkflo** [comment]
Thanks for your feedback and it's insightful.

Regarding your example, if you want two completely independent navigations, shouldn't you simply create two separate navigations and then toggle the particular sites that that navigation applies to?  

The core issue I'm reporting is simply when multiple sites are selected for a navigation AND propagation is disabled, then I think the user should expect that no changes being made on one site should affect the other site(s).  It all could be a UX issue but to me, that's a side effect and should be avoided..

Thanks for looking into it and hopefully improving it.  Looking forward to 1.4.8.

Best

**Comment by engram-design** [comment]
That's one way to do it for sure, but it does get a bit unwieldy to have "Main Menu - English", "Main Menu - French", "Main Menu - German", etc, rather than just a single "Main Menu" navigation where you can edit for each site. But there's also nothing stopping you from having a nav per site too.

And this is only an issue when you toggle this setting back and forth, A new navigation setting with this setting on or off wouldn't have this issue. It's because you're wanting to detach each sites' nodes from one another.
