### ISSUE TITLE
Internal Server error on GraphQL query with customAttributes 

### ISSUE THREAD

**Issue by kplebanSii** [verbb/navigation#242]
**Description**
When executing query with custom attributes Internal Server error occured.

**Steps to reproduce**
Execute Query:   
```
nodes {
   customAttributes {
      attribute
      value
    }
  }
```
Then graphQl throws an error:
```
  "errors": [
    {
      "debugMessage": "User Error: expected iterable, but did not find one for field navigation_Node.customAttributes.",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 5,
          "column": 7
        }
      ],
      "path": [
        "nodes",
        0,
        "customAttributes"
      ]
    },
 ]
```

It seems that empty customAttributes are saved differently for several nodes - sometimes is empty Array but sometimes is `null` and this is the cause of the error. 

**Additional info**
- Plugin version: 1.4.12
- Craft version: 3.5.12.1
- Multi-site: No
- Propagate nodes: Yes

**Additional context**

**Comment by engram-design** [comment]
I can't seem to replicate this. I've setup a new navigation with 3 nodes. One has `customAttributes` set to null, another an empty array and another with values.

```
{
  nodes (navHandle: "gql") {
    id
    customAttributes {
      attribute
      value
    }
  }
}
```

And the result:
```
{
  "data": {
    "nodes": [
      {
        "id": "17731",
        "customAttributes": null
      },
      {
        "id": "17732",
        "customAttributes": []
      },
      {
        "id": "17733",
        "customAttributes": [
          {
            "attribute": "Blah",
            "value": "Value"
          }
        ]
      }
    ]
  }
}
```

But - I am also testing this on Craft 3.5.17.1, I'm not sure if that makes a difference compared to 3.5.12.1.

However, I can certainly cast those attributes to an array, which they should be anyway. Should be fixed in [1.4.13](https://github.com/verbb/navigation/releases/tag/1.4.13)
