### ISSUE TITLE
Menu managed on a secondary site rendering links to primary site

### ISSUE THREAD

**Issue by russback** [verbb/navigation#247]
**Description**
I have 2 sites and a menu with the `Propagate nodes across all enabled sites?` disabled.

When I am in Site B and I create an Entry node, on the frontend, the menu renders URLs to Site A rather than Site B, i.e. on click I end up leaving Site B and landing on Site A.

Template code looks as follows:

```twig
<ul class="menu">
    {% nav node in craft.navigation.nodes('primaryNavigation').all %}
        <li {% if node.hasDescendants %}class="menu-item-has-children"{% endif %}>
            {{ node.link }}
            {% ifchildren %}
                <ul class="sub-menu">
                    {% children %}
                </ul>
            {% endifchildren %}
        </li>
    {% endnav %}
</ul>
```

**Additional info**
- Plugin version: 1.4.13
- Craft version: 3.6.6
- Multi-site: Yes
- Propagate nodes: No

**Comment by engram-design** [comment]
So with Propagation disabled, you manage navigation nodes for each navigation independently. Can you confirm on each navigation that you're picking the entry using the correct site?

![image](https://user-images.githubusercontent.com/1221575/108822349-1133dd80-7613-11eb-81c0-6fdcfab4ad1d.png)

For example, the above image you can select entries, but you can potentially select entries from other sites (by design).

**Comment by russback** [comment]
Completely missed that site menu - sorry!
