### ISSUE TITLE
navigation_nodes not migrating with project-config/apply

### ISSUE THREAD

**Issue by jjohnlaw** [verbb/navigation#258]
**Description**
I have a project with 3 different navs all populated with nodes. When merging the branch into my dev branch the Navs get transferred fine but the nodes do not:

![image](https://user-images.githubusercontent.com/14894660/117471780-1e911080-af50-11eb-8672-79d7847018af.png)

![image](https://user-images.githubusercontent.com/14894660/117471679-08835000-af50-11eb-831c-a0b8380abdc8.png)

I had a different dev try to merge and he had the same issue. 

On further inspection when i make changes to the nodes (re-order, edit, add, remove) it does not alter any project config files. Is this correct behaviour?

**Steps to reproduce**
1. Create navs with nodes on a craft install with `'allowAdminChanges' => true, 'devMode' => true`
2. Merge branch into different branch
3. `composer install `
4. `php craft project-config/apply `(also tried with adding `--force`)

**Additional info**
- Plugin version: 1.4.15
- Craft version:Craft Pro 3.6.11.2
- Multi-site: Yes
- Propagate nodes: Yes

**Comment by engram-design** [comment]
That's correct behaviour. Navigation nodes are considered content, being elements - the same as an Entry, Category etc. As such, they're not stored in project config for the same reason entries aren't. Because their content can change on multiple environments, like a client can edit a navigation's nodes on the production environment, that would clash with a stored node if it _were_ stored in project config.

If they were stored in the project config, you would have to have `allowAdminChanges => true` enabled on all environments, otherwise clients simply wouldn't be able to edit nodes on a production site.
