### ISSUE TITLE
Nested item can't be brought to top level if previous top level item has children

### ISSUE THREAD

**Issue by fernakr** [verbb/navigation#283]
Versions:
- Navigation 1.4.24
- Craft 3.7.35
 
Steps to replicate:
- Add a nested menu item i.e. a child item 
- Try to drag menu item to top level if the previous top level item has children
   -If the previous top level item doesn't have children or if there is no previous top level item, then it can be dragged to that position

**Comment by engram-design** [comment]
Yeah, I've noticed this is kind of a weird thing with Craft itself. We actually use the JS that Craft uses for structures with elements like entries, categories, etc. I can replicate the exact same behaviour.

I'll have to file an issue with Craft about this.

**Comment by fernakr** [comment]
That makes sense. Thanks for the info and filing with Craft!

**Comment by acalvino4** [comment]
Just came here to file this same issue.

@engram-design where does this happen in Craft? I actually don't have this issue with structures.

**Comment by engram-design** [comment]
Looks like you're right, this no longer seems to be an issue in Craft itself. Although it looks like they're using a different control with the `StructureTableSorter` which handles this much better. It also allows you to easily move things from left to right, changing the levels easier.

I think I'll be adding this to the refactor in Navigation 2.0.0 as it's a little more involved. This'll be more inline with the tableview Craft itself uses, and incorporate the element slide-out pane instead of the HUD to edit navigation nodes.

**Comment by engram-design** [comment]
This has been fixed in [2.0.0-beta.4](https://github.com/verbb/navigation/releases/tag/2.0.0-beta.4) for Craft 4
