### ISSUE TITLE
The node type returns the class path instead of the node label

### ISSUE THREAD

**Issue by TomDeSmet** [verbb/navigation#300]
**Description**
If I check a node's `type` property it returns `craft\elements\Entry`.
This should return the DisplayName of the node instead.

For example with my custom node type "Divider" I get this back: `modules\utilitiesmodule\navigation\DividerType` instead of the display name.

If I use `getTypeLabel()` it returns the correct name. Maybe this can be changed or added as an alternative property?

**Additional info**
- Plugin version: 2.0.0
- Craft version: 4.0.2
- Multi-site: Yes
- Propagate nodes: Yes

**Comment by engram-design** [comment]
Nope, this is correct behaviour, as `type` returns the class reference to the node type. This is because all nodes have a type for consistency (apart from element-type nodes which return the class for the element being linked to).

You could also use `{{ displayName(node.type) }}` which achieves the same thing as `{{ node.getTypeLabel() }}`.

Using the class name helps to prevent collisions where you might have multiple node types with the same "display name", but from a different plugin or module. It's unlikely for this to happen, and the main reason for the change was around consistently.

But I'll also say, compared to Craft 3, this is largely unchanged behaviour. `node.type` has always returned the class for element nodes, and custom node types. It's really just the addition of `verbb\navigation\nodetypes\CustomType` that should be the change.

It's also keeping consistency with similar scenarios for Craft/Craft Commerce when using `type` for things.
