### ISSUE TITLE
A&M migration throws a "Site Settings cannot be blank" error

### ISSUE THREAD

**Issue by aaronbushnell** [verbb/navigation#303]
**Description**
I'm not positive this is the case, but it looks like commit dba86a1 made the [siteSettings attribute of the Nav model required](https://github.com/verbb/navigation/commit/dba86a1356249b268c1cffc89246f034b92baa1c#diff-790ee0b46fb1e71f2e0df2cf70b6b7ba23f80eeaf60be4a76e0debc4f897d647R80).

Because it's not set on the A&M (or Navee) migration process it throws an error that this value is not set.

**Steps to reproduce**
1. Seed a database that has A&M Navigation data
2. Initiate an A&M Navigation migration process

**Additional info**
- Plugin version: 2.0.2
- Craft version: Craft Pro 4.0.5.1
- Multi-site: No
- Propagate nodes: N/A

**Comment by aaronbushnell** [comment]
And, sorry, I suppose this is true of version 1.4.26 also for folks stuck on Craft 3!

**Comment by engram-design** [comment]
Good point, I'd actually considered taking out these migration, because they're really only applicable to Craft 2/3, and we don't support going from Craft 2 to Craft 4 (same as Craft itself doesn't support that).

**Comment by engram-design** [comment]
This should be fixed in Navigation 1, and these migrations have been removed in Navigation 2 (for Craft 4), where they're no longer applicable. You'll need to perform the migrations from these Craft 2 plugins on Craft 3, before migrating to Craft 4 and beyond. 

It's a bit annoying, but mimics how the rest of the Craft ecosystem works with staggered upgrades.
