### ISSUE TITLE
How to know if current has disabled Navigation

### ISSUE THREAD

**Issue by xinningsu** [verbb/navigation#331]
### Question

I have multiple sites set up. in `Site Settings`, I disable one site, I don't want navigation to show in that site.
but using `craft.navigation.nodes` can still get nav urls back. so how do I know if current site has disabled Navigation? thanks

### Additional context

Craft: 3.7
Navigation: 1.4.28

**Comment by engram-design** [comment]
So ideally, the nodes themselves would be unavailable in the disabled site. But that's tricky depending on your propagation settings. We can't delete a node for one site, if you have it set to propagate, because that would delete the node for all sites.

I'll see what I can do with adding a query parameter for like `enabledForSite` or similar. This _maybe_ should be enabled by default (to only fetch nodes for the current site, if enabled in the nav settings), but that'll be a breaking change. I'll look into it however.

In the meantime, your best bet is to first fetch the nav, check if the enabled site's include the current site, and only query your nodes if they are:

```twig
{% set nav = craft.navigation.getNavByHandle('myMenu') %}

{% if currentSite.id in nav.getSiteIds() %}
    {% set nodes = craft.navigation.nodes(nav.handle).all() %}

    {# ... #}
{% endif %}
```

**Comment by xinningsu** [comment]
thanks. works.
By the way, it's `getEditableSiteIds()` instead of `getSiteIds()`

**Comment by engram-design** [comment]
Ah yes, you mentioned Navigation 1.4 for Craft 3, that's correct. `nav.getSiteIds()` for Navigation 2/Craft 4.
