### ISSUE TITLE
Performance penalty while using custom fields on navigation nodes

### ISSUE THREAD

**Issue by gglnx** [verbb/navigation#343]
### Describe the bug

I went down a rabbit hole to track some performance leaks on a site I'm currently working on. If I'm accessing a custom field on a navigation node I get for the first call a performance penalty of around 200ms-250ms, because the plugin triggers a complete read and parsing of the project configuration (my project configuration is quite large) from disk while querying all navigations.

The call flow: `$node->myCustomField -> Element::__get('myCustomField') -> Element->fieldByHandle('myCustomField') -> Node->getFieldLayout() -> Node->getNav() -> Navs->_createNavQuery()`

In `src/services/Navs.php` on line 713 is `Craft::$app->getProjectConfig()->get('plugins.navigation.schemaVersion', true)` called, which because of the second parameters triggers a whole read and parse from disk. If I remove the second parameter the penalty is away.

Is this nessary? I don't know if `->_navs()` will be called within migrations or project configuration changes where this may be nessary. Maybe adding a `$force` parameter to `->_navs()` could help?

### Steps to reproduce

1. Create a navigation with a custom field
2. Fill navigation
3. Access navigation with custom fields in frontend

### Craft CMS version

4.3.8

### Plugin version

2.0.16

### Multi-site?

Yes

**Comment by engram-design** [comment]
That is indeed an excellent point. Under normal use, we do want to typically load up the entire project config for things like saving the navs, but there's no real such need to do here. As you say, there's some performance benefits by not doing this full-blown check (but it's still an important check due to added query params to querying nodes). in migrations, we tend not to use service functions like these to prevent issues.

Fixed for the next release. To get the fix early, change your `verbb/navigation` requirement in `composer.json` to:

```
"require": {
  "verbb/navigation": "dev-craft-4 as 2.0.16",
  "...": "..."
}
```

Then run `composer update`.

**Comment by engram-design** [comment]
[2.0.17](https://github.com/verbb/navigation/releases/tag/2.0.17)
