### ISSUE TITLE
Spacing is a bit weird after entering a new link.

### ISSUE THREAD

**Issue by bob-pixeldeluxe** [verbb/navigation#383]
### Describe the bug

When i add a new entry and drag it under another navigation item (make it level 2). The drag icon is not placed correctly which makes the overview a bit messy till you refresh especially when you are working with a big navigation with dropdowns etc. 
<img width="424" alt="Screenshot 2024-02-05 at 11 14 06" src="https://github.com/verbb/navigation/assets/50947605/eac04a3b-a004-4729-9d56-4bca890365a7">

### Steps to reproduce

1. create a new link in the navigation plugin
2. drag it under something else.
3. the drag icon is placed a bit to the left till you refresh

### Craft CMS version

4.7.1

### Plugin version

2.0.25

### Multi-site?

Yes

**Comment by engram-design** [comment]
That's pretty odd, but you're right. There's two different pixel values for a server-rendered node and one that's been moved to a different level.

![CleanShot 2024-02-06 at 12 39 32@2x](https://github.com/verbb/navigation/assets/1221575/4a3cdd7d-3a86-428b-94c1-724681183670)

Because this inherits from Craft's structure view, we're not doing anything custom. In fact, I see this same behaviour in Craft's entries:

![CleanShot 2024-02-06 at 12 42 16@2x](https://github.com/verbb/navigation/assets/1221575/a9d79930-8b8f-4a84-9f88-786c791edc6f)

So I'll file an issue upstream at Craft.

**Comment by engram-design** [comment]
Looks to be fixed in Craft 4.7.2.
