### ISSUE TITLE
Multi Language Support don't work.

### ISSUE THREAD

**Issue by angrotheman** [verbb/navigation#55]
### Description

I have a Site with 6 Languages.
The Navigation URLs don´t change if I switch the Language. What did I wrong?
For example:
EN works fine - If I switch to ES the navigation still link to the EN pages.

Template Code:
```
{% set nodes = craft.navigation.nodes('main').all() %}
	<ul class="main">
	    {% nav node in nodes %}
	        <li>
	            {{ node.link }}
	           {% ifchildren %}
	               <ul>
	                   {% children %}
	               </ul>
	           {% endifchildren %}
	       </li>
	   {% endnav %}
	</ul>
```

### Steps to reproduce

1. Create a new Nav
2. Enable Propagate nodes
3. Have minimum 2 Languages

### Additional info

- Plugin version: 1.0.18
- Craft version: 3.0.36

**Comment by piotrpog** [comment]
Same here! I think its pretty serius problem.

In my case - i dont use `node.link` but `node.url` and `node.title`, but i get same result as @angrotheman .

One more detail to complement @angrotheman bug description. 

Plugin saves CURRENT language during adding menu code. If user is switched in control panel to for example second language, second language version of entry/category will appear on menu - and it will stay that way on ALL language versions of site.

**Comment by blackstalk** [comment]
Im having this issue as well.

It seems that when adding new navigation entries in the CP, the item propagates the same language entry for all sites.

Plugin Version:
**1.0.18**

Craft Version:
**3.1.3**

**Comment by piotrpog** [comment]
I have created walkaround for now. Even if node is using wrong language version of element, ID of this element stays the same. Using this ID, we can query correct version of element, like this:
```
{% set correctNode= craft.entries().siteId(currentSite.id).id(node.element.id).one() %}
```
Code above assumes node is entry.

**Comment by engram-design** [comment]
The reason for this complexity is that we're battling with localised navigation nodes and localised linked elements. This can be desirable, so a navigation isn't restricted to only linking elements from the same site as the navigation is.

For example, say you have a nav for your English site, but want to have a link in your nav to a particular entry's English and German version. You can create a node and select those elements for their respective sites. Your English nav doesn't have to contain just English elements, and vice versa.

Where this gets tricky is that how should Navigation act when you add a node to your English nav. Should it propagate the same linked element to your other nav items (currently does), or should it know to fetch the German version of the linked element and use that?

So, if you have `Propagate nodes across all enabled sites?` set for your nav, your navs will contain the same node and linked entry across those. If you want them to be different, you'll need to turn this setting off, and manage each nav's nodes.

But, as of [1.1.0](https://github.com/verbb/navigation/releases/tag/1.1.0), this behaviour has been changed to reflect what I believe a lot of people are after. If you add a node for one sites' nav, it'll automatically fetch the respective element for any other site and populate that. Unfortunately, this will need to be done manually, as this propagation only happens when you add a new node to the nav. Otherwise, the migration I could've written would likely produce duplicate nodes in your nav.

I know that's a long explanation!
