### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by hassanmah** [verbb/navigation#83]
### Description
I tried installing the plugin, but it got interrupted mid install. Now I'm trying to install the plugin again and I keep getting this error:

![image](https://user-images.githubusercontent.com/3025707/54693036-e1722600-4b1d-11e9-872c-963067205deb.png)

It will says 'Not installed' in plugin settings. I've tried removing and reinstalling through the Plugin store but get the same error

Any idea what I need to do?

Thanks

### Additional info

- Plugin version: 1.1.11
- Craft version: Craft Pro 3.0.36

**Comment by terdelyi** [comment]
@hassanmah I'm experiencing the same issues, but if you go back to 1.1.8 the `getProjectConfig()` call won't be a part of the plugin.

Verbb: Please use semantic versioning correctly. Project Config is a CraftCMS 3.1 feature which is still in beta. Any breaking changes should be in a major version.

**Comment by engram-design** [comment]
Sorry about this, I'd forgotten to increment the required version to Craft 3.1 where Project Config is supported. You'll either need to upgrade to Craft 3.1.x, or downgrade the Navigation plugin to 1.1.8. I've also modified the releases to reflect this so it won't happen again for Craft 3.0.x installs.

@terdelyi Project Config isn't really in beta, and this functionality doesn't really warrant a major version, because it isn't a breaking change (it is only because of my mistake).
