### ISSUE TITLE
Allow for Navigations to be created even when allowAdminChanges = false

### ISSUE THREAD

**Issue by neokoenig** [verbb/navigation#88]
At the moment, in order to add a new Navigation, I have to do it locally as our prod/staging locks project.yaml / allowAdminChanges = false.

I'd argue that creating a new navigation is actually a content issue; I've got a pagebuilder matrix where I can slot in existing navigations, but really, in that context, they need to be actual content items. Will there ever be scope for this?

**Comment by mtnorthrop** [comment]
I would like to see this as well. I have clients who would like to update navigations, but we would still like to set `allowAdminChanges` to false so they don't install Craft and plugin updates directly in production.

**Comment by engram-design** [comment]
Navigation _Nodes_ are always editable, as they are indeed content. Much the same way that entries are editable across environments. However, if you want to create new navigations, that's similar to creating a new entry type - I would consider that a site structure setting.

If a client wants to add a new navigation to the page, it won't just magically appear in your templates right? You'd need to update your templates to actually output the navigation in question.

Your use-case @neokoenig is an excellent example where I would agree is valid. Unfortunately, as navigations (again, not their nodes) are saved in the project config, they are tied to that content. If you add new navigations on staging/production, it will be out of sync with your local environment. The only solution is to remove Project Config support for this plugin.

I'll have to give this some thought.

See also https://github.com/verbb/navigation/issues/78 and https://github.com/verbb/navigation/issues/64 where this was asked to be included.

**Comment by mtnorthrop** [comment]
@engram-design, thanks for your response; I appreciate you taking the time to explain. It appears I misunderstood what the recent updates entail and, at least for my use case, it's perfectly fine that end users are not able to create new menus, just as long as they're able to add, edit, and remove links from existing menus.

**Comment by roberttolton** [comment]
I have an edge-case for this, I know, but for me I have a plugin that updates a Craft site's navigation with JSON data imported from a Shopify site's menu system.

I created my own plugin that talks to the `Navigation` plugin service, and essentially backs-up the current navigation, and creates a new one with the old one's handle. So a pull-down sync is achieved keeping the 'child' Craft site's menu in-sync with the 'parent' Shopify site.

I've obviously now found out that these syncs cause the `project.yaml` file to be changed. I do agree with the statements above that adding / removing navigations is much more than just a content change, but in my edge case, I'm just replacing a nav - keeping the handles the same.

**Comment by engram-design** [comment]
@roberttolton We're in a really tricky situation now that we've switched to project config, and there's no really a way to turn it off without losing it altogether. I completely get your use-case is valid, but its currently not possible (with Craft) to make these changes with `allowAdminChanges = false`.

Having said that, I've just added a config setting `bypassProjectConfig` in [1.2.5](https://github.com/verbb/navigation/releases/tag/1.2.5) which bypasses a few things with PC. Be aware that if you use this, nav's won't be saved to project config at all when creating new ones. This means that the file will immediately become out of sync.

You still can't manually create a new nav with this (the new button is still hidden), but it should work for programatic cases as per @roberttolton 

In addition - how often exactly would the structure of a navigation change from Shopify in order to pull down? Sure, nodes can change, and there's nothing project config related with nodes.

**Comment by roberttolton** [comment]
@engram-design Thanks for the config setting. With regards to how often the structure changes, I guess in terms of "could I update a nav, instead of creating a new one" that would be possible. However the main decision behind the create-new approach was being able to have a 'backup' nav that could be switched back to with just a handle change. Incase something went wrong with the import that wasn't caught. If Navigations implemented a kind of entry-versioning (if that would even be possible), could solve this.

**Comment by engram-design** [comment]
@roberttolton Ah, gotcha - that's fair enough! Hopefully the above will assist.
